// صفحة لإدارة البانرات - يمكن الوصول إليها عبر /admin/banners
"use client";
import BannerAdmin from "../../components/BannerAdmin";

export default function BannersAdminPage() {
  return (
    <div style={{ padding: "20px", minHeight: "100vh", background: "#f5f5f5" }}>
      <div style={{ textAlign: "center", marginBottom: "30px" }}>
        <h1 style={{ color: "#333", marginBottom: "10px" }}>إدارة البانرات</h1>
        <p style={{ color: "#666", fontSize: "16px" }}>
          أضف وأدر البانرات التي تظهر في الصفحة الرئيسية
        </p>
      </div>

      <BannerAdmin />

      <div
        style={{
          maxWidth: "600px",
          margin: "30px auto",
          padding: "20px",
          background: "white",
          borderRadius: "10px",
          boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
        }}
      >
        <h2 style={{ color: "#333", marginBottom: "15px" }}>معلومات مهمة:</h2>
        <div style={{ color: "#555", lineHeight: "1.6" }}>
          <p>
            <strong>مخطط قاعدة البيانات:</strong>
          </p>
          <pre
            style={{
              background: "#f8f9fa",
              padding: "15px",
              borderRadius: "5px",
              overflow: "auto",
              fontSize: "14px",
            }}
          >
            {`create table public."Banners" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  image text null,
  link text null,
  constraint Banners_pkey primary key (id)
);`}
          </pre>

          <p>
            <strong>موقع البانر:</strong>
          </p>
          <ul style={{ paddingRight: "20px" }}>
            <li>يظهر البانر فوق المنتجات وتحت التصنيفات الفرعية</li>
            <li>يدعم عرض عدة بانرات مع التناوب التلقائي</li>
            <li>يمكن أن يكون قابلاً للنقر أو غير قابل للنقر حسب وجود الرابط</li>
          </ul>

          <p>
            <strong>الميزات:</strong>
          </p>
          <ul style={{ paddingRight: "20px" }}>
            <li>تصميم متجاوب يتكيف مع جميع أحجام الشاشات</li>
            <li>دعم اللغة العربية والإنجليزية (RTL/LTR)</li>
            <li>تأثيرات انتقالية سلسة</li>
            <li>مؤشرات للتنقل بين البانرات</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
